### ISSUE TITLE
Documentation error in buf.build/docs/tutorials/getting-started-with-bsr/

### ISSUE THREAD

**Issue by pklewing** [bufbuild/buf-tour#15]
At https://buf.build/docs/tutorials/getting-started-with-bsr/#update-buf-gen-yaml the following documented `buf.gen.yaml` diff lines seem incorrect:

```
 -  - plugin: buf.build/protocolbuffers/go
 -    out: gen
 -    opt: paths=source_relative
```

If these lines get deleted as indicated there, not all required code will get generated, which again leads to follow-up errors in the tutorial. The finished code at https://github.com/bufbuild/buf-tour/blob/main/finish/getting-started-with-bsr/buf.gen.yaml also still includes these lines, which is also not in line with the above.

**Comment by rakuista** [comment]
This is fixed—thanks for the heads-up!
